[project]
name = 'crowdfunding-platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.crowdfunding]
path = 'contracts/crowdfunding.clar'
clarity_version = 2
epoch = 2.5

[contracts.dynamic-funding-tier]
path = 'contracts/dynamic-funding-tier.clar'
clarity_version = 3
epoch = 3.1

[contracts.milestone-escrow]
path = 'contracts/milestone-escrow.clar'
clarity_version = 3
epoch = 3.1

[contracts.reputation-trust-system]
path = 'contracts/reputation-trust-system.clar'
clarity_version = 3
epoch = 3.1

[contracts.campaign-update-scheduler]
path = 'contracts/campaign-update-scheduler.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
